### ISSUE TITLE
Can't compile in Swift due to non-modular header (CommonCrypto)

### ISSUE THREAD

**Issue by apersaud** [transloadit/TransloaditKit#2]
Trying to utilize this SDK with cocoapods as:
```ruby
pod 'TransloaditKit', git: 'https://github.com/transloadit/TransloaditKit'
```

and trying to build a sample app with it causes the error:
```
Include of non-modular header inside framework module TransloaditKit/NSString+Utils.h (line 10)
```

Just to confirm, will this be the supported SDK going forward? What is the sunset period for the older SDK?

**Comment by kvz** [comment]
/cc @MMasterson

As for the deprecation period, we won't pull that repo off the internet before TransloaditKit reaches stable and satisfies ~all customers. And even then it will probably be available for reference somewhere. But we'll be encouraging everyone to try TransloaditKit as it features tus.io, a responsive/approachable maintainer, and a number of other improvements over the ios-sdk. We'd surely be happy to learn what is still missing to make a good replacement besides this issue that you already reported tho, hat greatly helps us steer this in the right direction for our users.

**Comment by apersaud** [comment]
Thanks @kvz. I can definitely provide feedback once I can get things up and running with the new SDK. One thing that can be improved while we wait for code changes would be in the area of documentation (maybe including Swift examples), making sure Obj-C code is Swift 3 compatible (using macros so that objc function names are properly mapped to Swift). 

The example code provided seems a bit hard to read as well. It seems we are invoking the assembly (similar to the previous SD) inside the completion block of the same object? (Taken from [Example/TransloadIt/TransloaditViewController](https://github.com/transloadit/TransloaditKit/blob/master/Example/Transloadit/TransloaditViewController.m). Would be great if the example source code also had documentation.

```objc
transloadit.completionBlock = ^(NSDictionary* completionDictionary){
     [TestAssemblyWithSteps setUrlString:[completionDictionary valueForKey:@"assembly_ssl_url"]];
     [transloadit invokeAssembly:TestAssemblyWithSteps];       
};
```

Thanks

**Comment by MMasterson** [comment]
The pod hasn't been fully published. However I am taking your requests to heart and will make sure we have full Examples for Swift 3, 4 and better documentation.

The non-modular header error will be fixed in the next release of the SDK (which will be provided on CocoaPods) set to be released this week. 

*Edit:
@apersaud To mention on your point of invoking the assembly on the `assebmlyCompletionBlock`, that does not need to happen, it's done for the sake of a small and simple UI. You do however need to add the `assebmly_ssl_url` to the assembly object for when you do invoke.

**Comment by MMasterson** [comment]
For now, and due to `CommonCrypto` being a non-modular header, we use a modular version written in Swift  - `Arcane`- just import the dependency along with `TransloaditKit` as it shows in the `README`
