### ISSUE TITLE
How to add custom fields

### ISSUE THREAD

**Issue by RPJamie** [transloadit/TransloaditKit#27]
Using the SDK how do I add custom fields (like userid)? 

All the documentation on the site uses Web App as an example but I'm not sure how to set them on iOS using Swift.

**Comment by Acconut** [comment]
Yes, this should be possible. Please use the `addCustomParam` methods in the `Assembly` class: https://github.com/transloadit/TransloaditKit/blob/master/Transloadit/Classes/Assembly.swift#L38-L44

**Comment by RPJamie** [comment]
Thank you!

**Comment by Acconut** [comment]
You're welcome!
