### ISSUE TITLE
1.1.0 Release Goals

### ISSUE THREAD

**Issue by MMasterson** [transloadit/TransloaditKit#4]
Goals before release of TransloaditKit 1.1.0

**Changes to project**
- [x] Remove `Arcane` dependency 
- [ ] Add Websockets 
- [x] TUS Session networking tie-in
- - [x] Open TUS's Networking
- - [x] Transfer Transloadits calls to TUS Session
- - [x] Remove Transloadits own Session

**Support changes**
- [x] Updated Examples
- - [x] `Swift` Example
- - [x] `ObjC` Example
- - [x] Readme
- [x] Wiki Pages
- [x] Carthage Support

**Comment by nh7a** [comment]
Maybe you're no longer actively updating this SDK, I'd really like to see Carthage Support!

**Comment by MMasterson** [comment]
hey @nh7a this project is still active. Released the latest version about a month ago - TUSKit is also a major dependency for this project, and the latest version of that was released about a week ago! Just had some work conferences that took me away from this for a bit. But I have been settling back in and should have an updated version out in about a week. 

I can definitely get you some Carthage support!

**Comment by nh7a** [comment]
Hi @MMasterson Cool. I can't wait!

By the way, I reluctantly tried CocoaPod and found it didn't work well as-is because `pod 'Transloadit'` installs `Transloadit (1.0.4)` and `TUSKit (1.4.1)` but they are not compatible.  Since 1.0.6 (which is compatible with `TUSKit (1.4.1)`) hasn't been release, I think you'd need to modify `Transloadit (1.0.4)` to correctly depend on `TUSKit (1.4.0)` instead.

Meanwhile, I could install `1.0.6` by forcing `master` but I think this isn't as friendly to new comers ;-)
> pod 'Transloadit', :git => "https://github.com/transloadit/TransloaditKit.git", :branch => "master"

**Comment by zacksiri** [comment]
Will this be completed soon? We would like to use Transloadit for an upcoming project, and the last commit date is kind of an issue for us. Seems like there hasn't been activity in a while.

**Comment by MMasterson** [comment]
hey @zacksiri, there has been some work on a dependency used for the library, which should be wrapping soon. I can move this along in tandem. 

Day job had become pretty demanding over the last few months, but setting aside some time to finish. I will post a schedule tomorrow so you can get a better timeline.
 
Are there any key features you're looking to have so I can focus on those first?

**Comment by kvz** [comment]
I was trying to see if Transloadit-Client made it to a release, and found this thread. Can you update us on the status here @MMasterson?

**Comment by MMasterson** [comment]
@kvz this thread is a bit stale and should probably be closed - a rewrite in Swift has been introduced for sometime (version `2.x`), in-fact a new release was published today, mainly with `TUSKit` improvements.

A walkthrough was done with @Acconut a few months ago of the swift rewrite. A new thread of 2.0 goals should probably be introduced, or at least an updated readme with what's planned for next release. I can add this later today

**Comment by Acconut** [comment]
@MMasterson I am not able to find the string `Transloadit-Client` in the repo: 

![image](https://user-images.githubusercontent.com/1375043/111997373-469cef80-8b1b-11eb-9324-49c112e974a5.png)

Could you show us the place where the header is set? Or maybe did it got removed in the Swift rewrite?

**Comment by MMasterson** [comment]
@Acconut hm this might've been missed, I can add this weekend!

**Comment by Acconut** [comment]
Yes, please add it :)

**Comment by kvz** [comment]
Hey @MMasterson did you add it?
