### ISSUE TITLE
Does not build in swift environment

### ISSUE THREAD

**Issue by kvz** [transloadit/TransloaditKit#7]
As reported by @pushkardeshmukh1992 (for reference: https://app.intercom.io/a/apps/qiqpfgjg/inbox/inbox/all/conversations/15745376289) TransloaditKit does not build with the following error. Could you check it out @MMasterson?
 
![2018-04-13](https://user-images.githubusercontent.com/26752/38798643-68e31f52-4162-11e8-9df1-829413c1f89c.png)

Any more details you could add to this thread @pushkardeshmukh1992 are much appreciated 👌

**Comment by sheldon-sminq** [comment]
@MMasterson we have a production release around the corner, can we please get a version of 1.0.2 with Swift support ASAP.

**Comment by sheldon-sminq** [comment]
Any timeline for this? @MMasterson @kvz

**Comment by MMasterson** [comment]
@sheldon-sminq I'm taking a look into the issue now - will let know when I've got more info/a patch.

**Comment by MMasterson** [comment]
@sheldon-sminq Removed that dead-code and tested the build in a swift environment. You should be good to go now! Just update your pods and be sure `Transloadit` is coming down as `1.0.3`

**Comment by ssagare** [comment]
@MMasterson I downloaded your swift app demo but it gets crashed @ "NSURLSessionDataTask *postDataTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {    }];" In TransloaditRequest.m . I commented this lines then it worked but its returning server error. Could you please share working example of image & video upload both(Swift 3/4)

**Comment by MMasterson** [comment]
@ssagare what server error do you get?

**Comment by ssagare** [comment]
Bellow is log which I am getting after uploading image from demo example :
Transloadit_Example[10742:216382] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
2018-04-27 23:16:54.628928+0530 Transloadit_Example[10742:216293] <TUSResumableUpload.m:(321)> Server error, stopping
2018-04-27 23:16:55.411045+0530 Transloadit_Example[10742:216293] Here
2018-04-27 23:16:55.411359+0530 Transloadit_Example[10742:216293] https://api2-idun.transloadit.com/assemblies/f86f97c04a4211e89ababf1bb404f4a8
2018-04-27 23:16:56.128802+0530 Transloadit_Example[10742:216679] {
    "account_id" = a4f5a3d0238e11e89657618e1e5c5baa;
    "assembly_id" = f86f97c04a4211e89ababf1bb404f4a8;
    "assembly_ssl_url" = "https://api2-idun.transloadit.com/assemblies/f86f97c04a4211e89ababf1bb404f4a8";
    "assembly_url" = "http://api2.idun.transloadit.com/assemblies/f86f97c04a4211e89ababf1bb404f4a8";
    "bytes_expected" = 405;
    "bytes_received" = 405;
    "bytes_usage" = 0;
    "client_agent" = "Transloadit_Example/1.0 CFNetwork/897.15 Darwin/17.5.0";
    "client_ip" = "116.74.157.53";
    "client_referer" = "<null>";
    "executing_jobs" =     (
    );
    "execution_duration" = "0.169";
    "execution_start" = "2018/04/27 17:46:53 GMT";
    fields =     {
    };
    "has_dupe_jobs" = 0;
    "http_code" = 200;
    instance = "idun.transloadit.com";
    "is_infinite" = 0;
    "jobs_queue_duration" = 0;
    "last_job_completed" = "<null>";
    message = "The assembly was successfully completed.";
    "notify_duration" = "<null>";
    "notify_response_code" = "<null>";
    "notify_start" = "<null>";
    "notify_status" = "<null>";
    "notify_url" = "<null>";
    ok = "ASSEMBLY_COMPLETED";
    params = "{\"steps\":{\"encode\":{\"robot\":\"/image/resize\"}},\"auth\":{\"key\":\"****\",\"expires\":\"2018/04/27 17:51:51+00:00\"}}";
    "parent_assembly_status" = "<null>";
    "parent_id" = "<null>";
    "queue_duration" = "0.194";
    results =     {
    };
    "running_jobs" =     (
    );
    "start_date" = "2018/04/27 17:46:53 GMT";
    "started_jobs" =     (
    );
    template = "<null>";
    "template_id" = "<null>";
    "tus_url" = "https://api2-idun.transloadit.com/resumable/files/";
    "upload_duration" = "0.341";
    "upload_meta_data_extracted" = 1;
    uploads =     (
    );
    "uppyserver_url" = "https://api2-idun.transloadit.com/uppy-server/";
    warnings =     (
    );
    "websocket_url" = "https://api2-idun.transloadit.com/ws20111";
}

**Comment by sheldon-sminq** [comment]
@ssagare  @pushkardeshmukh1992 is this working? the issue seems to be closed. @MMasterson

**Comment by MMasterson** [comment]
@sheldon-sminq @pushkardeshmukh1992 @ssagare hey guys, I have reopened the issue and will have a patch up for you guys tomorrow

**Comment by sheldon-sminq** [comment]
@MMasterson its a little urgent as we have been stuck on this for a while now. Do let us know once the patch is ready. Also can we get an example of how to use the SDK with a template ID as we only use templates for our uploads and encoding.

**Comment by sheldon-sminq** [comment]
@MMasterson any progress on the same?

**Comment by sheldon-sminq** [comment]
@MMasterson @kvz my team has been waiting entire day, can we get any update on this today?

**Comment by MMasterson** [comment]
@sheldon-sminq  I have made progress in the patch but am waiting for a little more info on the assembly failure I am receiving. As you seem to be just using a template_id I'll post an example with that in a moment

**Comment by MMasterson** [comment]
@sheldon-sminq I am receiving a Transloadit error as well - once I get that cleared up I will be able to confirm the patch and release the new version

**Comment by sheldon-sminq** [comment]
@MMasterson when can we get an updated version ?

**Comment by pushkardeshmukh1992** [comment]
Hey @MMasterson, 
There are still few build issues.

I updated pod with _pod 'Transloadit', '~> 1.0.4'_
But installation fails when version is mentioned explicitly.

![image](https://user-images.githubusercontent.com/22586316/39744527-3265470e-52c2-11e8-8033-4d615910f292.png)

So I removed version and simply installed with _pod 'Transloadit'_. Here refer screenshot for installed dependancies. Transloadit 1.0.0 was installed with this.

![image](https://user-images.githubusercontent.com/22586316/39745314-83ac7810-52c4-11e8-853d-6d8a3beddf44.png)

To update it to 1.0.4, I updated pod and then the latest version was installed. Please refer screenshot below.

![image](https://user-images.githubusercontent.com/22586316/39745327-8dcf9390-52c4-11e8-8ba4-2e58f2dc132f.png)

After importing transloadit, there are few compile time errors. Please refer screenshots below.

![image](https://user-images.githubusercontent.com/22586316/39745087-e71b9738-52c3-11e8-92e5-984efa06253b.png)
![image](https://user-images.githubusercontent.com/22586316/39745053-d5692d3e-52c3-11e8-8a6f-dbf808b5724c.png)
![image](https://user-images.githubusercontent.com/22586316/39745027-bed8e226-52c3-11e8-8170-95c18957223c.png)

P.S: I am using **Swift 4**. Xcode version is **Version 9.3 (9E145)**

**Comment by pushkardeshmukh1992** [comment]
We have created a separate demo project to reproduce the same.
Please check [Transloadit Demo](https://github.com/ssagare/transloadit-demo).
