### ISSUE TITLE
SDK examples

### ISSUE THREAD

**Issue by sheldon-sminq** [transloadit/TransloaditKit#9]
We need a better set of examples on how to use the SDK, since we are using your paid service. Our iOS developers are not clear as to how to use the SDK for templates.

We are using templates for our video/image uploads.

**Comment by ssagare** [comment]
We need demo example for image & video upload using “Template” ( In swift 4) & it will be also helpful if you provide those example with sync as well as async methods similar to Android.

Right now in your demo swift app is getting crashed at line number 76 in TransloaditRequest.m i.e at 

NSURLSessionDataTask *postDataTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {  }];    
[postDataTask resume];

We tried out by commenting this lines but then we get the response but in that response we are not getting “Uploads” & “Results” array which are required us.

**Comment by MMasterson** [comment]
I will release an update tomorrow to fix #7 and will release updated docs along with it

**Comment by sheldon-sminq** [comment]
We have a template ID with predefined steps, how do we use this directly with the example?
***
       let Step1 = Step (key: "encode")
        Step1?.setValue("/image/resize", forOption: "robot")
        Step1?.setValue("75", forOption: "width")
        Step1?.setValue("75", forOption: "height")
        StepArray.add(Step1)
   These are not required as all steps are present in our template.
***

**Comment by MMasterson** [comment]
`
let template: Template = Template(templateId: "")
let assemblyWithTemplate = Assembly(template: template, andNumberOfFiles: 1)

**Comment by MMasterson** [comment]
@sheldon-sminq 
Make a `Template` object with the `template_id` as so:

```Swift
let template: Template = Template(templateId: "ID_HERE")
```

Then create an `Assembly` object with the `Template` object
```Swift
let assemblyWithTemplate = Assembly(template: template, andNumberOfFiles: 1)
```

Then you just need to create, and invoke the assembly like the rest of the example.

Do you have different syntax you'd like to see?
